# Generated by Django 5.1.8 on 2025-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_start_hour', models.IntegerField(default=9)),
                ('workday_end_hour', models.IntegerField(default=17)),
                ('timezone', models.CharField(default='UTC')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('interviewers', models.ManyToManyField(related_name='interview_template', to='interviews.interviewer')),
            ],
        ),
    ]
